name: SEDET - Manager

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  api-testing:
    uses: ./.github/workflows/karate-tests.yml

  ui-testing:
    needs: api-testing
    uses: ./.github/workflows/playwright.yml
    secrets: inherit
