name: Playwright Tests
on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: UI_Test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: UI_Test/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ROLE: ${{ secrets.ROLE }}

      # --- LÓGICA DE HISTÓRICO ---

      # 1. Baixa o que já está publicado no GitHub Pages para uma pasta temporária
      - name: Load Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true # Importante: evita erro se for a primeira vez
        with:
          ref: gh-pages
          path: gh-pages-dir

      # 2. Gera o novo report misturando os resultados atuais com o histórico baixado
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: UI_Test/allure-results
          allure_history: allure-report
          original_allure_history: gh-pages-dir # Pasta de onde ele puxa o passado
          keep_reports: 20 # Mantém as últimas 20 execuções no gráfico

      # 3. Publica o report atualizado (com o novo ponto no gráfico)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
